# Generated by Django 4.2.4 on 2023-09-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="snippet",
            field=models.CharField(
                default="Click Link Above To Read Blog Post...", max_length=250
            ),
        ),
    ]
